import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';
import { format } from 'date-fns';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 11, color: '#333' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, borderBottom: '2px solid #D6689C', paddingBottom: 10 },
  logo: { fontSize: 24, color: '#D6689C', fontWeight: 'bold' },
  title: { fontSize: 16, marginBottom: 8, marginTop: 15, color: '#D6689C', fontWeight: 'bold', textTransform: 'uppercase' },
  subHeader: { fontSize: 12, fontWeight: 'bold', marginBottom: 5, color: '#555', marginTop: 10 },
  
  // User Info Box
  userInfoBox: { border: '1px solid #E2E8F0', padding: 10, borderRadius: 5, marginBottom: 15, backgroundColor: '#F7FAFC' },
  row: { flexDirection: 'row', marginBottom: 4 },
  label: { width: 80, fontWeight: 'bold', color: '#718096' },
  value: { color: '#2D3748' },

  // Result Box
  resultBox: { padding: 15, borderRadius: 5, backgroundColor: '#FFF5F8', borderLeft: '5px solid #D6689C', marginBottom: 15 },
  riskText: { fontSize: 14, fontWeight: 'bold' },
  
  // Images
  chartImage: { width: '100%', height: 200, objectFit: 'contain', marginVertical: 10 },
  ultrasoundImage: { width: 250, height: 200, objectFit: 'contain', alignSelf: 'center', marginVertical: 10, borderRadius: 5, border: '1px solid #ddd' },

  // Lists
  bulletPoint: { marginLeft: 10, marginBottom: 4 },
  
  disclaimer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#A0AEC0', textAlign: 'center', borderTop: '1px solid #eee', paddingTop: 10 }
});

const PCOSReportPDF = ({ reportTitle, userData, testData, insights, diet, exercise, medical, chartImage, uploadedImage }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.logo}>PCOSmart</Text>
          <Text style={{ fontSize: 10, color: '#777' }}>AI-Powered Health Report</Text>
        </View>
        <View style={{ alignItems: 'flex-end' }}>
          <Text>{format(new Date(), 'PPP')}</Text>
          <Text style={{ fontSize: 10, color: '#777' }}>{reportTitle}</Text>
        </View>
      </View>

      {/* User Info */}
      <View style={styles.userInfoBox}>
        <View style={styles.row}><Text style={styles.label}>Name:</Text><Text style={styles.value}>{userData.name || 'N/A'}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Email:</Text><Text style={styles.value}>{userData.email || 'N/A'}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Age:</Text><Text style={styles.value}>{userData.age || 'N/A'}</Text></View>
      </View>

      {/* Result Section */}
      <Text style={styles.title}>Assessment Result</Text>
      <View style={styles.resultBox}>
        <Text style={styles.riskText}>Probability: {(testData.probability * 100).toFixed(1)}%</Text>
        <Text style={{ marginTop: 5 }}>Risk Level: {testData.probability > 0.7 ? 'High Risk' : testData.probability > 0.35 ? 'Moderate Risk' : 'Low Risk'}</Text>
      </View>

      {/* Ultrasound Image (If Exists) */}
      {uploadedImage && (
        <View>
          <Text style={styles.subHeader}>Analyzed Ultrasound Image</Text>
          <Image src={uploadedImage} style={styles.ultrasoundImage} />
        </View>
      )}

      {/* Insights */}
      <Text style={styles.title}>Clinical Insights</Text>
      <View>
        {insights.map((text, i) => <Text key={i} style={styles.bulletPoint}>• {text}</Text>)}
      </View>

      {/* Chart (If Exists) */}
      {chartImage && (
        <View>
          <Text style={styles.subHeader}>Symptom Analysis Chart</Text>
          <Image src={chartImage} style={styles.chartImage} />
        </View>
      )}

      {/* Action Plan */}
      <Text style={styles.title}>Personalized Action Plan</Text>
      
      <View style={{ marginBottom: 10 }}>
        <Text style={styles.subHeader}>🥗 Dietary Recommendations</Text>
        {diet?.map((text, i) => <Text key={i} style={styles.bulletPoint}>- {text}</Text>)}
      </View>

      <View style={{ marginBottom: 10 }}>
        <Text style={styles.subHeader}>🏋️‍♀️ Exercise Routine</Text>
        {exercise?.map((text, i) => <Text key={i} style={styles.bulletPoint}>- {text}</Text>)}
      </View>

      <View style={{ marginBottom: 10 }}>
        <Text style={styles.subHeader}>👩‍⚕️ Medical Advice</Text>
        {medical?.map((text, i) => <Text key={i} style={styles.bulletPoint}>- {text}</Text>)}
      </View>

      <Text style={styles.disclaimer}>
        IMPORTANT: This report is generated by an Artificial Intelligence model for educational and screening purposes only. 
        It is NOT a definitive medical diagnosis. Please present this report to a certified gynecologist or endocrinologist for clinical verification.
      </Text>
    </Page>
  </Document>
);

export default PCOSReportPDF;